name: Node.js CI

on: [push, pull_request]

jobs:
  test-sakuria:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies & test
        run: npm run test